# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metricCentral.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13metricCentral.proto\"%\n\x11\x46ileRequestMetric\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"%\n\x12\x46ileResponseMetric\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\x1e\n\x0bReplyMetric\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0b\x43hunkMetric\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\"\n\x0e\x46ileListMetric\x12\x10\n\x08\x66ileName\x18\x03 \x03(\t\"\"\n\x12HelloRequestMetric\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x10HelloReplyMetric\x12\x0f\n\x07message\x18\x01 \x01(\t2y\n\x0b\x46ileService\x12\x30\n\x10UploadFileMetric\x12\x0c.ChunkMetric\x1a\x0c.ReplyMetric(\x01\x12\x38\n\x0esayHelloMetric\x12\x13.HelloRequestMetric\x1a\x11.HelloReplyMetricb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metricCentral_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEREQUESTMETRIC']._serialized_start=23
  _globals['_FILEREQUESTMETRIC']._serialized_end=60
  _globals['_FILERESPONSEMETRIC']._serialized_start=62
  _globals['_FILERESPONSEMETRIC']._serialized_end=99
  _globals['_REPLYMETRIC']._serialized_start=101
  _globals['_REPLYMETRIC']._serialized_end=131
  _globals['_CHUNKMETRIC']._serialized_start=133
  _globals['_CHUNKMETRIC']._serialized_end=162
  _globals['_FILELISTMETRIC']._serialized_start=164
  _globals['_FILELISTMETRIC']._serialized_end=198
  _globals['_HELLOREQUESTMETRIC']._serialized_start=200
  _globals['_HELLOREQUESTMETRIC']._serialized_end=234
  _globals['_HELLOREPLYMETRIC']._serialized_start=236
  _globals['_HELLOREPLYMETRIC']._serialized_end=271
  _globals['_FILESERVICE']._serialized_start=273
  _globals['_FILESERVICE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
