# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import metricCentral_pb2 as metricCentral__pb2


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFileMetric = channel.stream_unary(
                '/FileService/UploadFileMetric',
                request_serializer=metricCentral__pb2.ChunkMetric.SerializeToString,
                response_deserializer=metricCentral__pb2.ReplyMetric.FromString,
                )
        self.sayHelloMetric = channel.unary_unary(
                '/FileService/sayHelloMetric',
                request_serializer=metricCentral__pb2.HelloRequestMetric.SerializeToString,
                response_deserializer=metricCentral__pb2.HelloReplyMetric.FromString,
                )


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFileMetric(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sayHelloMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFileMetric': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFileMetric,
                    request_deserializer=metricCentral__pb2.ChunkMetric.FromString,
                    response_serializer=metricCentral__pb2.ReplyMetric.SerializeToString,
            ),
            'sayHelloMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.sayHelloMetric,
                    request_deserializer=metricCentral__pb2.HelloRequestMetric.FromString,
                    response_serializer=metricCentral__pb2.HelloReplyMetric.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFileMetric(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/FileService/UploadFileMetric',
            metricCentral__pb2.ChunkMetric.SerializeToString,
            metricCentral__pb2.ReplyMetric.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sayHelloMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileService/sayHelloMetric',
            metricCentral__pb2.HelloRequestMetric.SerializeToString,
            metricCentral__pb2.HelloReplyMetric.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
